name: keyboard
description: "A feature containg the keyboard feature."
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.8.1
  flutter: ">=3.26.0"
resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^9.1.1

  language:

  widgetbook: ^3.14.3
  widgetbook_annotation: ^3.5.0
  injectable: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  build_runner: ^2.5.4
  widgetbook_generator: ^3.13.0
  injectable_generator: ^2.7.0
flutter:
