name: flyingdarts_mobile
description: A flutter app to send score to Flyingdarts.net
publish_to: none

version: 1.3.9+1

environment:
  sdk: ^3.10.0
  flutter: ">=3.38.6"
resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  # Workspace packages - these are now managed by the workspace configuration
  api_sdk: ^0.0.1
  app_config_core: ^0.0.1
  app_config_prefs: ^0.0.1
  app_config_secrets: ^0.0.1
  core: ^0.0.1
  internationalization: ^0.0.1
  keyboard: ^0.0.1
  language: ^0.0.1
  profile: ^0.0.1
  speech: ^1.0.0
  splash: ^0.0.1
  ui: ^0.0.1
  websocket: ^0.0.1

  flyingdarts_authress_login: ^0.0.2-dev.3

  # External dependencies
  bloc: ^9.2.0
  curved_navigation_bar: ^1.0.6
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.2.3
  get_it: ^9.2.0
  go_router: ^17.0.1
  injectable: ^2.7.1+4
  loading_animation_widget: ^1.3.0
  lottie: ^3.3.2
  provider: ^6.1.5+1
  speech_to_text: ^7.3.0
  widgetbook: ^3.20.2
  widgetbook_annotation: ^3.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  alchemist: ^0.13.0
  bloc_test: ^10.0.0
  build_runner: ^2.10.4
  equatable: ^2.0.8
  flutter_gherkin: 2.0.0
  flutter_inappwebview: ^6.1.5
  flutter_lints: ^6.0.0
  gherkin: ^3.1.0
  glob: ^2.1.3
  injectable_generator: ^2.12.0
  intl: ^0.20.2
  mockito: ^5.6.1
  rxdart: ^0.28.0
  test: ^1.29.0
  widgetbook_generator: ^3.20.1

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/icons/fd_icon.svg
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

