name: language
description: "A package containg the language feature."
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.10.0
  flutter: ">=3.38.6"
resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^9.1.1
  get_it: ^9.2.0

  speech_to_text: ^7.3.0

  ui: ^0.0.1
  app_config_core: ^0.0.1
  app_config_prefs: ^0.0.1

  injectable: ^2.7.1+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  build_runner: ^2.10.4
  injectable_generator: ^2.8.1

flutter:
