name: websocket
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.10.0
  flutter: ">=3.38.6"
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flyingdarts_authress_login:
    path: ../../authress/login
  rxdart: ^0.28.0
  web_socket_channel: ^3.0.3
  injectable: ^2.7.1+4
  json_annotation: ^4.9.0
  get_it: ^9.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.9.5
  mockito: ^5.6.1
  injectable_generator: ^2.8.1
  build_runner: ^2.10.4

flutter:
