name: app_config_prefs
description: A flutter package containing preferences configuration
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.8.1
  flutter: ">=3.26.0"
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  app_config_core:
  shared_preferences: ^2.5.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
