name: app_config_core
description: A flutter package containing readable and writeable configurations
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.8.1
  flutter: ^3.26.0
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.9.5
  build_runner: ^2.5.4

flutter:
