name: api_sdk
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.10.0
  flutter: ">=3.38.6"
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  injectable: ^2.7.1+4
  json_annotation: ^4.9.0
  equatable: ^2.0.8
  dio: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.11.3
  mockito: ^5.6.1
  build_runner: ^2.10.4

flutter:
