name: speech
description: "A production-ready speech recognition package with scalable architecture."
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.8.1
  flutter: ">=3.26.0"
resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^9.1.1

  # Dependency Injection
  get_it: ^8.0.3
  injectable: ^2.5.0

  # Utilities
  equatable: ^2.0.7
  logger: ^2.0.2+1

  # Speech Recognition
  speech_to_text: ^7.2.0

  # Configuration
  app_config_core:
  app_config_prefs:

  # UI Components
  ui:
  language:

  # Development & Testing
  widgetbook: ^3.14.3
  widgetbook_annotation: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # Code Generation
  build_runner: ^2.5.4
  widgetbook_generator: ^3.13.0
  injectable_generator: ^2.7.0

  # Testing
  bloc_test: ^10.0.0
  mockito: ^5.4.4
  mocktail: ^1.0.3

flutter:
