name: speech
description: "A production-ready speech recognition package with scalable architecture."
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.10.0
  flutter: ">=3.38.6"
resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^9.1.1

  # Dependency Injection
  get_it: ^9.2.0
  injectable: ^2.7.1+4

  # Utilities
  equatable: ^2.0.8
  logger: ^2.6.2

  # Speech Recognition
  speech_to_text: ^7.3.0

  # Configuration
  app_config_core: ^0.0.1
  app_config_prefs: ^0.0.1

  # UI Components
  ui: ^0.0.1
  language: ^0.0.1

  # Development & Testing

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # Code Generation
  build_runner: ^2.10.4
  injectable_generator: ^2.8.1

  # Testing
  bloc_test: ^10.0.0
  mockito: ^5.6.1
  mocktail: ^1.0.4

flutter:
