name: flyingdarts_authress_login
description: A Dart/Flutter package for Authress authentication with widget-based authentication guards
homepage: https://flyingdarts.net
repository: https://github.com/flyingdarts/flyingdarts/tree/main/packages/frontend/flutter/authress/login
version: 0.0.2-dev.3

environment:
  sdk: ^3.8.1
  flutter: ">=3.26.0"
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  webview_flutter: ^4.4.2
  url_launcher: ^6.2.1
  shared_preferences: ^2.2.2
  jwt_decode: ^0.3.1
  crypto: ^3.0.3

  go_router: ^16.0.0
  app_links: ^6.3.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.7
  fake_async: ^1.3.1
  mocktail: ^1.0.3

flutter:

