name: ui
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.8.1
  flutter: ^3.26.0
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  lottie: ^3.1.2
  widgetbook: ^3.14.3
  widgetbook_annotation: ^3.5.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  build_runner: ^2.5.4
  widgetbook_generator: ^3.13.0
flutter:
