name: Main .NET Workflow (Development)
on:
  workflow_call:
  push:
    branches:
      - development
    paths:
      - "apps/backend/dotnet/**"
      - "packages/backend/dotnet/**"
      - ".github/workflows/main_dotnet_dev.yml"
      - "flyingdarts.sln"
jobs:
  build-authorizer-dev:
    uses: ./.github/workflows/build-dotnet-lambda.yml
    with:
      project-name: "flyingdarts.backend.authorizer"
      project-directory: "apps/backend/dotnet/authorizer"
      lambda-function-name: "Flyingdarts-Backend-Authorizer-Development"
      dotnet-version: "8.0.x"

  deploy-authorizer-dev:
    needs: build-authorizer-dev
    uses: ./.github/workflows/deploy-lambda.yml
    with:
      lambda-function-name: "Flyingdarts-Backend-Authorizer-Development"
      artifact-name: "Flyingdarts-Backend-Authorizer-Development-package"
      environment: "development"
    secrets: inherit

  build-signalling-api-dev:
    uses: ./.github/workflows/build-dotnet-lambda.yml
    with:
      project-name: "flyingdarts.backend.signalling.api"
      project-directory: "apps/backend/dotnet/signalling/api"
      lambda-function-name: "Flyingdarts-Signalling-Api-Development"
      dotnet-version: "8.0.x"
      node-version: "22"

  deploy-signalling-api-dev:
    needs: build-signalling-api-dev
    uses: ./.github/workflows/deploy-lambda.yml
    with:
      lambda-function-name: "Flyingdarts-Signalling-Api-Development"
      artifact-name: "Flyingdarts-Signalling-Api-Development-package"
      environment: "development"
    secrets: inherit

  build-x01-api-dev:
    uses: ./.github/workflows/build-dotnet-lambda.yml
    with:
      project-name: "flyingdarts.backend.api"
      project-directory: "apps/backend/dotnet/api"
      lambda-function-name: "Flyingdarts-Backend-Api-Development"
      dotnet-version: "8.0.x"
      node-version: "22"

  deploy-x01-api-dev:
    needs: build-x01-api-dev
    uses: ./.github/workflows/deploy-lambda.yml
    with:
      lambda-function-name: "Flyingdarts-Backend-Api-Development"
      artifact-name: "Flyingdarts-Backend-Api-Development-package"
      environment: "development"
    secrets: inherit

  build-friends-api-dev:
    uses: ./.github/workflows/build-dotnet-lambda.yml
    with:
      project-name: "flyingdarts.backend.friends.api"
      project-directory: "apps/backend/dotnet/friends"
      lambda-function-name: "Flyingdarts-Friends-Api-Development"
      dotnet-version: "8.0.x"
      node-version: "22"

  deploy-friends-api-dev:
    needs: build-friends-api-dev
    uses: ./.github/workflows/deploy-lambda.yml
    with:
      lambda-function-name: "Flyingdarts-Friends-Api-Development"
      artifact-name: "Flyingdarts-Friends-Api-Development-package"
      environment: "development"
    secrets: inherit
