name: Main Production Workflow

on:
  workflow_dispatch:
  pull_request:
    branches:
      - production

jobs:
  build-angular:
    name: Build Angular
    uses: ./.github/workflows/ci-angular-app-production.yml
    secrets: inherit
