name: Main Angular Workflow (Staging)
on:
  workflow_call:
  push:
    branches:
      - staging
    paths:
      - "apps/frontend/angular/**"
      - ".github/workflows/main_angular_staging.yml"
      - "angular.json"
jobs:
  build-angular-staging:
    uses: ./.github/workflows/build-angular-app.yml
    with:
      project-name: "fd-app"
      project-directory: "apps/frontend/angular/fd-app"
      configuration: "staging"
      environment: "staging"
      node-version: "22"

  deploy-angular-staging:
    needs: build-angular-staging
    uses: ./.github/workflows/deploy-angular-app.yml
    with:
      project-name: "fd-app"
      environment: "staging"
    secrets:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_DEPLOYMENT_ROLE_ARN: ${{ secrets.AWS_DEPLOYMENT_ROLE_ARN }}
      AWS_CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID_STAGING }}
