name: Dart Game Test

on:
  workflow_call:
  push:
    branches:
      - staging
    paths:
      - "e2e/**"
      - ".github/workflows/run-dart-game-test.yml"
jobs:
  authress-token:
    uses: ./.github/workflows/authress-token.yml
    secrets:
      AUTHRESS_API_URL: ${{ secrets.AUTHRESS_API_URL }}
      AUTHRESS_SERVICE_CLIENT_ACCESS_KEY: ${{ secrets.AUTHRESS_SERVICE_CLIENT_ACCESS_KEY }}
  e2e-test:
    runs-on: ubuntu-latest
    needs: authress-token
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Build & Install
      run: dotnet build
      working-directory: e2e

    - name: Ensure browsers are installed
      run: pwsh bin/Debug/net9.0/playwright.ps1 install --with-deps
      working-directory: e2e

    - name: Run your tests
      env:
        AUTHRESS_TOKEN: ${{ env.token }}
      run: dotnet test
      working-directory: e2e
