name: Angular Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        
      - name: Install Angular CLI
        run: npm install -g @angular/cli  

      - name: Build
        id: build
        run: |
          ERROR_OUTPUT=$(ng build --prod 2>&1) || true
          echo "::set-output name=build_errors::$ERROR_OUTPUT"

      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_DEVELOPMENT_ENDPOINTS_CHANNEL_WEBHOOK }}
          embed-title: "Flyingdarts.Angular"
          embed-description: ${{ env.ERROR_OUTPUT }}
          embed-footer-text: ${{ github.ref_name }}
          embed-timestamp: ${{ github.event.head_commit.timestamp }}
          embed-author-name: ${{ github.event.head_commit.author }}
