name: Angular Build

on:
  push:
    branches:
      - main

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Angular CLI
        run: npm install -g @angular/cli

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js from Setup
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Use Angular CLI from Setup
        run: npm link @angular/cli

      - name: Build the application
        uses: mathiasvr/command-output@v2.0.0
        continue-on-error: true
        id: build
        with: 
          run: ng build

      - name: Write output into a file
        run: echo "${{ steps.build.outputs.stderr }}" > build_output.txt

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js from Setup
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Use Angular CLI from Setup
        run: npm link @angular/cli

      - name: Running tests
        uses: mathiasvr/command-output@v2.0.0
        continue-on-error: true
        id: test
        with: 
          run: ng test

      - name: Write output into a file
        run: echo "${{ steps.test.outputs.stdout }}" > test_output.txt
 
  log-to-discord:
    name: Log to Discord
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - name: Log build output to discord
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_DEVELOPMENT_ENDPOINTS_CHANNEL_WEBHOOK }}
          content: 'Build logs: Flyingdarts.Angular'
          filename: build_output.txt

      - name: Log test output discord
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_DEVELOPMENT_ENDPOINTS_CHANNEL_WEBHOOK }}
          content: 'Test logs: Flyingdarts.Angular'
          filename: test_output.txt