name: Angular Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        
      - name: Install Angular CLI
        run: npm install -g @angular/cli  
        
      - name: Build
        id: build
        run: |
          ERROR_OUTPUT=$(ng build 2>&1) || true
          echo "build_errors=${ERROR_OUTPUT}" >> $GITHUB_STATE

      - name: Encode build errors
        run: |
          BUILD_ERRORS_ENCODED=$(echo "${{ steps.build.outputs.build_errors }}" | base64)
          echo "build_errors_encoded=${BUILD_ERRORS_ENCODED}" >> $GITHUB_STATE

      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_DEVELOPMENT_ENDPOINTS_CHANNEL_WEBHOOK }}
          embed-title: Flyingdarts.Angular
          embed-description: ${{ env.GITHUB_STATE_build_errors_encoded }}
