name: Dart Game Test

on:
  workflow_call:
  push:
    branches:
      - staging
    paths:
      - "e2e/**"
      - ".github/workflows/run-dart-game-test.yml"
jobs:
  authress_token:
    uses: mikepattyn/flyingdarts/.github/workflows/authress-token.yml@staging
    secrets:
      AUTHRESS_API_URL: ${{ secrets.AUTHRESS_API_URL }}
      AUTHRESS_SERVICE_CLIENT_ACCESS_KEY: ${{ secrets.AUTHRESS_SERVICE_CLIENT_ACCESS_KEY }}
  e2e-test:
    runs-on: ubuntu-latest
    needs: authress_token
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Build & Install
      run: dotnet build
      working-directory: e2e

    - name: Ensure browsers are installed
      run: pwsh bin/Debug/net9.0/playwright.ps1 install --with-deps
      working-directory: e2e

    - name: Verify token is present
      env:
        AUTHRESS_TOKEN: ${{ needs.authress_token.outputs.token }}
      run: |
        if [ -z "$AUTHRESS_TOKEN" ]; then
          echo "AUTHRESS_TOKEN is missing" >&2
          exit 1
        fi
        echo "::add-mask::$AUTHRESS_TOKEN"
        echo "AUTHRESS_TOKEN length: ${#AUTHRESS_TOKEN}"

    - name: Run your tests
      env:
        AUTHRESS_TOKEN: ${{ needs.authress_token.outputs.token }}
      run: dotnet test
      working-directory: e2e
