name: Signalling API Lambda (Development)

on:
  workflow_call:
  push:
    paths:
      - "apps/backend/dotnet/signalling/**"
      - "packages/backend/dotnet/**"
      - "tools/dotnet/**"

  pull_request:
    paths:
      - "apps/backend/dotnet/signalling/**"
      - "packages/backend/dotnet/**"
      - "tools/dotnet/**"

jobs:
  build-signalling-api-dev:
    uses: ./.github/workflows/build-dotnet-lambda.yml
    with:
      project-name: "flyingdarts.backend.signalling.api"
      project-directory: "apps/backend/dotnet/signalling/api"
      lambda-function-name: "Flyingdarts-Backend-Signalling-Api-Development"
      dotnet-version: "8.0.x"
      node-version: "22"

  deploy-signalling-api-dev:
    needs: build-signalling-api-dev
    uses: ./.github/workflows/deploy-lambda.yml
    with:
      lambda-function-name: "Flyingdarts-Backend-Signalling-Api-Development"
      artifact-name: "Flyingdarts-Backend-Signalling-Api-Development-package"
      environment: "development"
    secrets: inherit
