name: X01 API Lambda (Development)

on:
  workflow_call:
  push:
    paths:
      - "apps/backend/dotnet/api/**"
      - "packages/backend/dotnet/**"

  pull_request:
    paths:
      - "apps/backend/dotnet/api/**"
      - "packages/backend/dotnet/**"

jobs:
  check-changes:
    uses: ./.github/workflows/beachball-checkchange.yml
    with:
      project-name: "flyingdarts.backend.games.x01.api"
      node-version: "22"

  build-x01-api-dev:
    uses: ./.github/workflows/build-dotnet-lambda.yml
    with:
      project-name: "flyingdarts.backend.games.x01.api"
      project-directory: "apps/backend/dotnet/api"
      lambda-function-name: "Flyingdarts-Backend-Games-X01-Api-Development"
      dotnet-version: "8.0.x"
      node-version: "22"

  deploy-x01-api-dev:
    needs: build-x01-api-dev
    uses: ./.github/workflows/deploy-lambda.yml
    with:
      lambda-function-name: "Flyingdarts-Backend-Games-X01-Api-Development"
      artifact-name: "Flyingdarts-Backend-Games-X01-Api-Development-package"
      environment: "development"
    secrets: inherit
