name: X01 API Lambda (Development)

on:
  workflow_call:
  push:
    branches:
      - development
    paths:
      - "apps/backend/dotnet/api/**"
      - "packages/backend/dotnet/**"
      - ".github/workflows/x01-api-development.yml"

jobs:
  build-x01-api-development:
    uses: ./.github/workflows/build-dotnet-lambda.yml
    with:
      project-name: "flyingdarts.backend.api"
      project-directory: "apps/backend/dotnet/api"
      lambda-function-name: "Flyingdarts-Backend-Api-Development"
      dotnet-version: "8.0.x"
      node-version: "22"

  deploy-x01-api-development:
    needs: build-x01-api-development
    uses: ./.github/workflows/deploy-lambda.yml
    with:
      lambda-function-name: "Flyingdarts-Backend-Api-Development"
      artifact-name: "Flyingdarts-Backend-Api-Development-package"
      environment: "development"
    secrets: inherit
